"""Docker Builder — Generates Docker artifacts for the generated project.

Satisfies Extended Feature: Dockerisation of the generated project (5 pts).
"""

from pathlib import Path
from typing import Optional

from forgeai.core.activity_logger import ActivityLogger


class DockerBuilder:
    """Generates Dockerfile, docker-compose.yml, and .dockerignore for the output project."""

    def __init__(self, project_dir: str, logger: Optional[ActivityLogger] = None):
        self._project_dir = Path(project_dir).resolve()
        self._logger = logger

    def generate_docker_files(self, base_image: str = "python:3.11-slim"):
        """Generate all Docker artefacts inside the generated project directory."""
        self._project_dir.mkdir(parents=True, exist_ok=True)
        self._write_dockerfile(base_image)
        self._write_compose()
        self._write_dockerignore()
        if self._logger:
            self._logger.info(
                "DockerBuilder",
                "Docker artefacts generated: Dockerfile, docker-compose.yml, .dockerignore",
            )

    # ── Private helpers ────────────────────────────────────────────────────

    def _write_dockerfile(self, base_image: str):
        content = f"""\
# Auto-generated by ForgeAI
FROM {base_image}

WORKDIR /app

# Install dependencies first (layer-cached)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source
COPY . .

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \\
    CMD python -c "import httpx; httpx.get('http://localhost:8000/health')" || exit 1

# Use uvicorn for production-grade ASGI serving
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        self._write(self._project_dir / "Dockerfile", content)

    def _write_compose(self):
        content = """\
# Auto-generated by ForgeAI
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///./app.db}
      - SECRET_KEY=${SECRET_KEY:-changeme-in-production}
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_data:
"""
        self._write(self._project_dir / "docker-compose.yml", content)

    def _write_dockerignore(self):
        content = """\
# Auto-generated by ForgeAI
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
.env
.env.*
*.db
*.sqlite3
.git/
.gitignore
.forgeai/
tests/
*.log
.pytest_cache/
.coverage
htmlcov/
dist/
build/
*.egg-info/
"""
        self._write(self._project_dir / ".dockerignore", content)

    @staticmethod
    def _write(path: Path, content: str):
        path.write_text(content, encoding="utf-8")
